---
kind: pipeline
name: default

steps:
  - name: docker-new-registry
    image: plugins/docker
    settings:
      repo: ktruckenmiller/aws-cli
      tags: latest
      username:
        from_secret: username
      password:
        from_secret: password

  - name: docker-old-registry
    image: plugins/docker
    settings:
      repo: ktruckenmiller/awscli
      tags: latest
      username:
        from_secret: username
      password:
        from_secret: password
