---
kind: pipeline
name: default

steps:
  - name: docker-new-registry
    image: plugins/docker
    settings:
      repo: ktruckenmiller/aws-cli
      tags: "v2"
      username:
        from_secret: username
      password:
        from_secret: password

  - name: docker-old-registry
    image: plugins/docker
    settings:
      repo: ktruckenmiller/awscli
      tags: "v2"
      username:
        from_secret: username
      password:
        from_secret: password

# trigger:
#   branch: "v2"
#   event: push
