---
# pipeline:
#   build:
#     image: plugins/docker
#     repo: ktruckenmiller/aws-cli
#     secrets: [ docker_username, docker_password ]
kind: pipeline
name: default

steps:
- name: frontend
  image: plugins/docker
  settings:
    repo: ktruckenmiller/aws-cli
    tags: latest
    username:
      from_secret: username
    password:
      from_secret: password

# - name: backend
#   image: golang
#   commands:
#   - go build
#   - go test
