version: 0.2

phases:
  pre_build:
    commands:
      - docker pull python:alpine
  build:
    commands:
      - docker build -t ktruckenmiller/aws-cli:latest .
  post_build:
    commands:
      - docker login -p $(aws ssm get-parameter --name /dockerhub/password --region us-east-1 --query Parameter.Value --output text --with-decryption) -u ktruckenmiller
      - docker push ktruckenmiller/aws-cli:latest
